### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by zeke** [bevacqua/highlight-redux#2]
I've been down the dark highlight.js + browserify road [before](https://github.com/isagalaev/highlight.js/pull/553), so I'm happy to see this package, but I'm not sure how to use it. Can you add some documentation?

**Comment by bevacqua** [comment]
See https://github.com/bevacqua/ultramarked/blob/master/package.json

I'll add documentation

**Comment by zeke** [comment]
Ah the `browser` property, I see. Nice. Is it documented somewhere now?

**Comment by bevacqua** [comment]
It's in the [`#usage` section](https://github.com/bevacqua/highlight-redux#usage) in the readme
